# Generated by Django 4.0.4 on 2023-07-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailSender', '0002_rename_uploadedfile_csv_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSV_files',
            new_name='Uploaded_File',
        ),
    ]
