# Generated by Django 4.0.4 on 2023-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailSender', '0004_remove_uploaded_file_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_file',
            name='file_content',
            field=models.TextField(),
        ),
    ]
